"""
Allergieausweis Memory Trainer
==============================
A Streamlit app to train memorising batches of 4 or 8 "Allergieausweis" cards,
then test recall (fill in missing fields) or knowledge/aggregate questions,
score the result, and track progress over time.

Run locally:   streamlit run app.py
Data:          cards.db  (generated by generate_db.py)
Faces:         faces/  (recursively scanned for *.png/*.jpg; user-supplied)
Save state:    Download / Upload a JSON file from the sidebar.
"""

import io
import json
import random
import sqlite3
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st
from PIL import Image, ImageDraw

# --------------------------------------------------------------------------- #
#  Config
# --------------------------------------------------------------------------- #
APP_DIR = Path(__file__).parent
DB_PATH = APP_DIR / "cards.db"
FACES_DIR = APP_DIR / "faces"
PROGRESS_FILE = APP_DIR / "progress.json"   # local convenience save (cloud = ephemeral)

MONTHS = ["Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli",
          "August", "September", "Oktober", "November", "Dezember"]
BLOOD = ["A", "B", "AB", "0"]
# Distractor pool for "knowledge" questions (allergies). Kept in sync with generator.
ALLERGY_POOL = [
    "Soja", "Schnitzel", "Pasta", "Tomaten", "Erdnüsse", "Milch", "Eier",
    "Weizen", "Pollen", "Hausstaub", "Katzenhaare", "Latex", "Nickel",
    "Sonnencreme", "Sauerstoff", "Schnee", "Burger", "Penicillin", "Ibuprofen",
    "Aspirin", "Rituximab", "Cortison", "Insulin", "Batterien", "Ratten",
    "Gold", "Brillen", "Pflanzen", "Autos", "Elfen", "Geldscheine", "Steine",
    "Wolken", "Regen", "Bücher", "Telefone", "Schuhe", "Fenster", "Türen",
    "Kissen", "Lampen", "Stühle", "Wasser", "Feuer", "Musik", "Farben",
    "Spiegel", "Uhren", "Schlüssel", "Tische",
]

st.set_page_config(page_title="Allergieausweis Trainer", page_icon="🪪", layout="wide")

# --------------------------------------------------------------------------- #
#  Data loading (cached)
# --------------------------------------------------------------------------- #
@st.cache_data(show_spinner=False)
def load_cards():
    if not DB_PATH.exists():
        return []
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM cards ORDER BY id").fetchall()
    conn.close()
    cards = []
    for r in rows:
        d = dict(r)
        d["allergies"] = json.loads(d["allergies"])
        d["takes_medication"] = bool(d["takes_medication"])
        cards.append(d)
    return cards


@st.cache_data(show_spinner=False)
def load_faces():
    """Recursively glob faces/, return a deterministic sorted list of paths."""
    if not FACES_DIR.exists():
        return []
    exts = ("*.png", "*.PNG", "*.jpg", "*.jpeg", "*.JPG", "*.JPEG")
    files = []
    for ext in exts:
        files.extend(FACES_DIR.rglob(ext))
    return sorted(str(f) for f in files)


@st.cache_data(show_spinner=False)
def placeholder_face(seed: int):
    """Gray placeholder used when no faces folder is present."""
    img = Image.new("RGB", (180, 200), (220, 220, 224))
    d = ImageDraw.Draw(img)
    d.ellipse((60, 40, 120, 100), fill=(180, 180, 186))      # head
    d.ellipse((45, 110, 135, 210), fill=(180, 180, 186))     # shoulders
    d.text((58, 175), "Foto", fill=(120, 120, 126))
    return img


def face_for(card, faces):
    if faces:
        return faces[card["face_index"] % len(faces)]
    return placeholder_face(card["face_index"])


CARDS = load_cards()
FACES = load_faces()

# --------------------------------------------------------------------------- #
#  Session state
# --------------------------------------------------------------------------- #
def init_state():
    ss = st.session_state
    ss.setdefault("phase", "home")          # home | study | recall | quiz | results
    ss.setdefault("batch_ids", [])          # ids of current batch
    ss.setdefault("batch_size", 4)
    ss.setdefault("history", [])            # list of result dicts
    ss.setdefault("test", None)             # built test payload
    ss.setdefault("last_result", None)
    # try loading local progress once
    ss.setdefault("_loaded_local", False)
    if not ss["_loaded_local"]:
        ss["_loaded_local"] = True
        if PROGRESS_FILE.exists():
            try:
                data = json.loads(PROGRESS_FILE.read_text())
                ss["history"] = data.get("history", [])
                ss["batch_ids"] = data.get("batch_ids", [])
                ss["batch_size"] = data.get("batch_size", 4)
            except Exception:
                pass


init_state()


def current_batch():
    by_id = {c["id"]: c for c in CARDS}
    return [by_id[i] for i in st.session_state["batch_ids"] if i in by_id]


def save_payload():
    return {
        "history": st.session_state["history"],
        "batch_ids": st.session_state["batch_ids"],
        "batch_size": st.session_state["batch_size"],
        "saved_at": datetime.now().isoformat(timespec="seconds"),
    }


def autosave_local():
    try:
        PROGRESS_FILE.write_text(json.dumps(save_payload(), ensure_ascii=False, indent=2))
    except Exception:
        pass


# --------------------------------------------------------------------------- #
#  Card rendering (study view, styled like the sheets)
# --------------------------------------------------------------------------- #
CARD_CSS = """
<style>
.aw-card{border:1px solid #c9ced6;border-radius:14px;padding:0;overflow:hidden;
         background:#fafbfc;margin-bottom:8px;}
.aw-head{display:flex;justify-content:space-between;align-items:center;
         padding:8px 14px;border-bottom:2px solid #d23b3b;font-weight:700;
         font-size:1.05rem;}
.aw-cross{color:#d23b3b;font-weight:900;font-size:1.4rem;line-height:1;}
.aw-field{font-size:0.92rem;margin:1px 0;}
.aw-label{color:#444;}
</style>
"""


def render_card(card, faces, show_country=True, hide=None):
    """hide: set of field keys to blank out (for partially shown study/preview)."""
    hide = hide or set()
    st.markdown(CARD_CSS, unsafe_allow_html=True)
    with st.container(border=True):
        st.markdown(
            "<div class='aw-head'><span>Allergieausweis</span>"
            "<span class='aw-cross'>✚</span></div>", unsafe_allow_html=True)
        c1, c2 = st.columns([1, 2.4])
        with c1:
            st.image(face_for(card, faces), width='stretch')
        with c2:
            def line(label, value, key):
                val = "▢▢▢" if key in hide else value
                st.markdown(
                    f"<div class='aw-field'><span class='aw-label'>{label}:</span> "
                    f"<b>{val}</b></div>", unsafe_allow_html=True)
            line("Name", card["name"], "name")
            line("Geburtsdatum", f'{card["birth_day"]}. {card["birth_month"]}', "date")
            line("Medikamenteneinnahme", "ja" if card["takes_medication"] else "nein", "meds")
            line("Blutgruppe", card["blood_group"], "blood")
            line("Bekannte Allergien", ", ".join(card["allergies"]), "allergies")
            line("Ausweisnummer", card["serial"], "serial")
            if show_country:
                line("Ausstellungsland", card["country"], "country")


# --------------------------------------------------------------------------- #
#  Test builders
# --------------------------------------------------------------------------- #
def build_recall_test(batch, include_identify):
    return {
        "type": "recall",
        "include_identify": include_identify,
        "card_ids": [c["id"] for c in batch],
    }


def build_quiz(batch, rng):
    """Generate a mixed set of aggregate + knowledge questions from the batch."""
    qs = []
    serials = [c["serial"] for c in batch]

    # --- aggregate: count a digit across all serials ---
    digit = rng.choice("0123456789")
    cnt = sum(s.count(digit) for s in serials)
    qs.append({"kind": "num",
               "prompt": f"Wie oft kommt die Ziffer **{digit}** in allen "
                         f"Ausweisnummern dieses Batches zusammen vor?",
               "answer": cnt})

    # --- aggregate: how many take medication ---
    qs.append({"kind": "num",
               "prompt": "Wie viele Personen nehmen Medikamente (ja)?",
               "answer": sum(1 for c in batch if c["takes_medication"])})

    # --- aggregate: count a blood group ---
    bg = rng.choice(BLOOD)
    qs.append({"kind": "num",
               "prompt": f"Wie viele Personen haben Blutgruppe **{bg}**?",
               "answer": sum(1 for c in batch if c["blood_group"] == bg)})

    # --- aggregate: count a month ---
    month = rng.choice([c["birth_month"] for c in batch])
    qs.append({"kind": "num",
               "prompt": f"Wie viele Personen haben im **{month}** Geburtstag?",
               "answer": sum(1 for c in batch if c["birth_month"] == month)})

    # --- knowledge: was this name in the batch? (true / decoy) ---
    if rng.random() < 0.5:
        real = rng.choice(batch)
        qs.append({"kind": "choice", "options": ["ja", "nein"],
                   "prompt": f"War der Name **{real['name']}** in diesem Batch?",
                   "answer": "ja"})
    else:
        names = {c["name"] for c in batch}
        fake = rng.choice(batch)["name"]
        # mutate a letter so it's not in batch
        while fake in names:
            i = rng.randrange(len(fake))
            fake = fake[:i] + rng.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ") + fake[i + 1:]
        qs.append({"kind": "choice", "options": ["ja", "nein"],
                   "prompt": f"War der Name **{fake}** in diesem Batch?",
                   "answer": "nein"})

    # --- knowledge: which allergy did <name> have? ---
    card = rng.choice(batch)
    correct = rng.choice(card["allergies"])
    distractors = [a for a in ALLERGY_POOL if a not in card["allergies"]]
    opts = rng.sample(distractors, 3) + [correct]
    rng.shuffle(opts)
    qs.append({"kind": "choice", "options": opts,
               "prompt": f"Welche dieser Allergien hatte **{card['name']}**?",
               "answer": correct})

    # --- knowledge: which country issued <name>'s card? ---
    card = rng.choice(batch)
    countries = list({c["country"] for c in CARDS})
    distractors = [c for c in countries if c != card["country"]]
    opts = rng.sample(distractors, min(3, len(distractors))) + [card["country"]]
    rng.shuffle(opts)
    qs.append({"kind": "choice", "options": opts,
               "prompt": f"In welchem Land wurde der Ausweis von "
                         f"**{card['name']}** ausgestellt?",
               "answer": card["country"]})

    # --- knowledge with image: who is this (match face -> name)? ---
    if len(batch) >= 2:
        card = rng.choice(batch)
        others = [c for c in batch if c["id"] != card["id"]]
        opts_cards = rng.sample(others, min(3, len(others))) + [card]
        rng.shuffle(opts_cards)
        qs.append({"kind": "face",
                   "prompt": "Wie heißt die abgebildete Person?",
                   "face_id": card["id"],
                   "options": [c["name"] for c in opts_cards],
                   "answer": card["name"]})

    rng.shuffle(qs)
    return {"type": "quiz", "questions": qs, "card_ids": [c["id"] for c in batch]}


# --------------------------------------------------------------------------- #
#  Sidebar
# --------------------------------------------------------------------------- #
def sidebar():
    ss = st.session_state
    with st.sidebar:
        st.header("🪪 Allergieausweis Trainer")

        if not CARDS:
            st.error("Keine cards.db gefunden. Bitte `python generate_db.py` ausführen.")
        if not FACES:
            st.info("Kein faces/-Ordner gefunden. Platzhalter werden angezeigt.")
        else:
            st.caption(f"{len(FACES)} Gesichter geladen · {len(CARDS)} Karten")

        st.divider()
        st.subheader("Neuer Batch")
        size = st.radio("Batch-Größe", [4, 8],
                        index=0 if ss["batch_size"] == 4 else 1, horizontal=True)
        ss["batch_size"] = size
        if st.button("🎲 Neuen Batch ziehen", width='stretch', type="primary",
                     disabled=not CARDS):
            ids = random.sample([c["id"] for c in CARDS], size)
            ss["batch_ids"] = ids
            ss["phase"] = "study"
            ss["test"] = None
            ss["last_result"] = None
            autosave_local()
            st.rerun()

        if ss["batch_ids"]:
            if st.button("👁 Aktuellen Batch ansehen", width='stretch'):
                ss["phase"] = "study"
                st.rerun()

        st.divider()
        st.subheader("💾 Speichern / Laden")
        st.download_button(
            "⬇️ Fortschritt herunterladen",
            data=json.dumps(save_payload(), ensure_ascii=False, indent=2),
            file_name="allergie_fortschritt.json",
            mime="application/json", width='stretch')
        up = st.file_uploader("⬆️ Fortschritt laden (JSON)", type=["json"],
                              label_visibility="collapsed")
        if up is not None and st.button("Laden bestätigen", width='stretch'):
            try:
                data = json.loads(up.read().decode("utf-8"))
                ss["history"] = data.get("history", [])
                ss["batch_ids"] = data.get("batch_ids", [])
                ss["batch_size"] = data.get("batch_size", 4)
                ss["phase"] = "home"
                autosave_local()
                st.success("Fortschritt geladen.")
                st.rerun()
            except Exception as e:
                st.error(f"Konnte Datei nicht lesen: {e}")

        st.divider()
        n = len(ss["history"])
        if n:
            avg = sum(h["pct"] for h in ss["history"]) / n
            best = max(h["pct"] for h in ss["history"])
            st.metric("Durchläufe", n)
            cc1, cc2 = st.columns(2)
            cc1.metric("Ø Score", f"{avg:.0f}%")
            cc2.metric("Bester", f"{best:.0f}%")
        if st.button("🏠 Start / Übersicht", width='stretch'):
            ss["phase"] = "home"
            st.rerun()


# --------------------------------------------------------------------------- #
#  Phase: home / progress overview
# --------------------------------------------------------------------------- #
def view_home():
    st.title("Allergieausweis Memory Trainer")
    st.write("Ziehe links einen Batch mit 4 oder 8 Karten, präge sie dir ein, "
             "und teste dich danach im **Lückentest** (Felder reproduzieren) "
             "oder im **Wissensquiz** (Aggregat- und Zuordnungsfragen).")

    if st.session_state["batch_ids"]:
        b = current_batch()
        st.success(f"Aktiver Batch: {len(b)} Karten "
                   f"({', '.join(c['name'] for c in b)})")
        c1, c2, c3 = st.columns(3)
        if c1.button("👁 Ansehen", width='stretch'):
            st.session_state["phase"] = "study"; st.rerun()
        if c2.button("✍️ Lückentest", width='stretch'):
            start_test("recall"); st.rerun()
        if c3.button("❓ Wissensquiz", width='stretch'):
            start_test("quiz"); st.rerun()

    hist = st.session_state["history"]
    if hist:
        st.divider()
        st.subheader("📈 Fortschritt")
        df = pd.DataFrame(hist)
        df["Durchlauf"] = range(1, len(df) + 1)
        st.line_chart(df.set_index("Durchlauf")["pct"], y_label="Score (%)")
        show = df[["ts", "mode", "size", "score", "max", "pct"]].copy()
        show.columns = ["Zeit", "Modus", "Größe", "Punkte", "Max", "%"]
        st.dataframe(show.iloc[::-1], width='stretch', hide_index=True)
    else:
        st.info("Noch keine Durchläufe. Zieh links einen Batch, um zu starten.")


# --------------------------------------------------------------------------- #
#  Phase: study
# --------------------------------------------------------------------------- #
def view_study():
    batch = current_batch()
    st.title(f"Einprägen · {len(batch)} Karten")
    st.caption("Nimm dir Zeit. Wenn du bereit bist, wähle unten einen Test.")
    cols = st.columns(2)
    for i, card in enumerate(batch):
        with cols[i % 2]:
            render_card(card, FACES)
    st.divider()
    c1, c2, c3 = st.columns([1, 1, 1])
    if c1.button("✍️ Lückentest starten", type="primary", width='stretch'):
        start_test("recall"); st.rerun()
    if c2.button("❓ Wissensquiz starten", type="primary", width='stretch'):
        start_test("quiz"); st.rerun()
    if c3.button("🏠 Zurück", width='stretch'):
        st.session_state["phase"] = "home"; st.rerun()


def start_test(kind):
    ss = st.session_state
    batch = current_batch()
    if not batch:
        return
    if kind == "recall":
        ss["test"] = build_recall_test(batch, include_identify=False)
        ss["phase"] = "recall"
    else:
        rng = random.Random()  # fresh questions each time
        ss["test"] = build_quiz(batch, rng)
        ss["phase"] = "quiz"


# --------------------------------------------------------------------------- #
#  Phase: recall (fill in missing fields)
# --------------------------------------------------------------------------- #
def view_recall():
    ss = st.session_state
    test = ss["test"]
    batch = current_batch()
    include_id = test.get("include_identify", False)
    st.title("Lückentest")
    st.caption("Gesicht (und Name) sind vorgegeben. Reproduziere die übrigen Felder.")
    include_id = st.checkbox("Auch Name & Allergien abfragen (schwer)",
                             value=include_id)
    test["include_identify"] = include_id

    answers = {}
    for idx, card in enumerate(batch):
        with st.container(border=True):
            cc = st.columns([1, 3])
            with cc[0]:
                st.image(face_for(card, FACES), width='stretch')
            with cc[1]:
                if include_id:
                    name = st.text_input("Name", key=f"name_{idx}")
                else:
                    st.markdown(f"**Name:** {card['name']}")
                    name = None
                a, b = st.columns(2)
                day = a.text_input("Geburtstag (Tag)", key=f"day_{idx}")
                month = b.selectbox("Monat", ["—"] + MONTHS, key=f"month_{idx}")
                a, b = st.columns(2)
                meds = a.selectbox("Medikamente", ["—", "ja", "nein"], key=f"meds_{idx}")
                blood = b.selectbox("Blutgruppe", ["—"] + BLOOD, key=f"blood_{idx}")
                a, b = st.columns(2)
                serial = a.text_input("Ausweisnummer", key=f"serial_{idx}")
                country = b.text_input("Ausstellungsland", key=f"country_{idx}")
                if include_id:
                    allergies = st.text_input(
                        "Allergien (Komma-getrennt)", key=f"all_{idx}")
                else:
                    allergies = None
        answers[card["id"]] = dict(name=name, day=day, month=month, meds=meds,
                                   blood=blood, serial=serial, country=country,
                                   allergies=allergies)

    if st.button("✅ Auswerten", type="primary", width='stretch'):
        grade_recall(batch, answers, include_id)
        st.rerun()


def norm(s):
    return (s or "").strip().lower()


def grade_recall(batch, answers, include_id):
    details = []
    score = 0
    max_pts = 0
    for card in batch:
        a = answers[card["id"]]
        items = []

        # date (day + month together)
        date_ok = (norm(a["day"]) == str(card["birth_day"])
                   and a["month"] == card["birth_month"])
        items.append(("Geburtsdatum", f'{card["birth_day"]}. {card["birth_month"]}',
                      f'{a["day"] or "—"}. {a["month"]}', date_ok))

        meds_truth = "ja" if card["takes_medication"] else "nein"
        meds_ok = a["meds"] == meds_truth
        items.append(("Medikamente", meds_truth, a["meds"], meds_ok))

        blood_ok = a["blood"] == card["blood_group"]
        items.append(("Blutgruppe", card["blood_group"], a["blood"], blood_ok))

        serial_ok = norm(a["serial"]) == card["serial"]
        items.append(("Ausweisnummer", card["serial"], a["serial"] or "—", serial_ok))

        country_ok = norm(a["country"]) == norm(card["country"])
        items.append(("Ausstellungsland", card["country"], a["country"] or "—", country_ok))

        if include_id:
            name_ok = norm(a["name"]) == norm(card["name"])
            items.append(("Name", card["name"], a["name"] or "—", name_ok))
            given = {x.strip().lower() for x in (a["allergies"] or "").split(",") if x.strip()}
            truth = {x.lower() for x in card["allergies"]}
            inter = len(given & truth)
            all_ok = given == truth
            items.append((f"Allergien ({inter}/{len(truth)} richtig)",
                          ", ".join(card["allergies"]), a["allergies"] or "—", all_ok))

        for _, _, _, ok in items:
            max_pts += 1
            score += 1 if ok else 0
        details.append({"card": card, "items": items})

    finalize_result("Lückentest", score, max_pts, details)


# --------------------------------------------------------------------------- #
#  Phase: quiz
# --------------------------------------------------------------------------- #
def view_quiz():
    ss = st.session_state
    test = ss["test"]
    by_id = {c["id"]: c for c in CARDS}
    st.title("Wissensquiz")
    st.caption("Fragen zum gerade gelernten Batch.")

    answers = []
    for i, q in enumerate(test["questions"]):
        with st.container(border=True):
            st.markdown(f"**Frage {i+1}.** {q['prompt']}")
            if q["kind"] == "num":
                val = st.number_input("Antwort", min_value=0, step=1,
                                      key=f"q{i}", value=0)
                answers.append(("num", val))
            elif q["kind"] == "choice":
                val = st.radio("Antwort", q["options"], key=f"q{i}", index=None,
                               horizontal=len(q["options"]) <= 3)
                answers.append(("choice", val))
            elif q["kind"] == "face":
                card = by_id[q["face_id"]]
                cc = st.columns([1, 3])
                with cc[0]:
                    st.image(face_for(card, FACES), width='stretch')
                with cc[1]:
                    val = st.radio("Name", q["options"], key=f"q{i}", index=None)
                answers.append(("choice", val))

    if st.button("✅ Auswerten", type="primary", width='stretch'):
        grade_quiz(test, answers)
        st.rerun()


def grade_quiz(test, answers):
    details = []
    score = 0
    for q, (_, given) in zip(test["questions"], answers):
        if q["kind"] == "num":
            ok = int(given) == int(q["answer"])
        else:
            ok = given == q["answer"]
        score += 1 if ok else 0
        details.append({"prompt": q["prompt"],
                        "your": "—" if given is None else given,
                        "correct": q["answer"], "ok": ok})
    finalize_result("Wissensquiz", score, len(test["questions"]),
                    details, is_quiz=True)


# --------------------------------------------------------------------------- #
#  Results
# --------------------------------------------------------------------------- #
def finalize_result(mode, score, max_pts, details, is_quiz=False):
    ss = st.session_state
    pct = round(100 * score / max_pts) if max_pts else 0
    ss["history"].append({
        "ts": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "mode": mode, "size": len(ss["batch_ids"]),
        "score": score, "max": max_pts, "pct": pct,
    })
    ss["last_result"] = {"mode": mode, "score": score, "max": max_pts,
                         "pct": pct, "details": details, "is_quiz": is_quiz}
    ss["phase"] = "results"
    autosave_local()


def view_results():
    ss = st.session_state
    r = ss["last_result"]
    st.title("Ergebnis")
    c1, c2, c3 = st.columns(3)
    c1.metric("Modus", r["mode"])
    c2.metric("Punkte", f'{r["score"]} / {r["max"]}')
    c3.metric("Score", f'{r["pct"]}%')
    st.progress(r["pct"] / 100)

    st.divider()
    if r["is_quiz"]:
        for i, d in enumerate(r["details"], 1):
            icon = "✅" if d["ok"] else "❌"
            st.markdown(f"{icon} **{i}.** {d['prompt']}")
            if not d["ok"]:
                st.caption(f"Deine Antwort: {d['your']} · Richtig: **{d['correct']}**")
    else:
        for d in r["details"]:
            card = d["card"]
            with st.container(border=True):
                st.markdown(f"**{card['name']}**")
                rows = []
                for label, truth, yours, ok in d["items"]:
                    rows.append({"Feld": label, "Deine Antwort": yours,
                                 "Richtig": truth, "": "✅" if ok else "❌"})
                st.dataframe(pd.DataFrame(rows), hide_index=True,
                             width='stretch')

    st.divider()
    c1, c2, c3 = st.columns(3)
    if c1.button("🔁 Gleichen Batch erneut", width='stretch'):
        ss["phase"] = "study"; st.rerun()
    if c2.button("🎲 Neuer Batch", type="primary", width='stretch'):
        ids = random.sample([c["id"] for c in CARDS], ss["batch_size"])
        ss["batch_ids"] = ids
        ss["phase"] = "study"; ss["test"] = None
        autosave_local(); st.rerun()
    if c3.button("📈 Übersicht", width='stretch'):
        ss["phase"] = "home"; st.rerun()


# --------------------------------------------------------------------------- #
#  Router
# --------------------------------------------------------------------------- #
sidebar()
phase = st.session_state["phase"]
if not CARDS:
    st.title("Allergieausweis Trainer")
    st.error("Es wurde keine `cards.db` gefunden. Bitte zuerst "
             "`python generate_db.py` ausführen.")
elif phase == "study":
    view_study()
elif phase == "recall":
    view_recall()
elif phase == "quiz":
    view_quiz()
elif phase == "results":
    view_results()
else:
    view_home()
